-- Crear la tabla Alumnos
CREATE TABLE Alumnos (
  ALM_ID INT PRIMARY KEY AUTO_INCREMENT,
  ALM_NAME VARCHAR(255) NOT NULL,
  ALM_SURNAME VARCHAR(255) NOT NULL,
  ALM_FECHA VARCHAR(255) NOT NULL,
  ALM_NIA INT NOT NULL
  );

-- Crear la tabla Moduls
CREATE TABLE Modulos (
  MOD_ID INT PRIMARY KEY AUTO_INCREMENT,
  MOD_NAME VARCHAR(255) NOT NULL
);

-- Crear la tabla Matricules
CREATE TABLE Matriculas (
  MAT_ID INT PRIMARY KEY AUTO_INCREMENT,
  MAT_ALM_ID INT NOT NULL,
  MAT_MOD_ID INT NOT NULL,
  MAT_NOTAS TEXT,

  FOREIGN KEY (MAT_ALM_ID) REFERENCES Alumnos(ALM_ID),
  FOREIGN KEY (MAT_MOD_ID) REFERENCES Modulos(MOD_ID)
);