/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.actividad_4;

import java.awt.Dimension;
import java.awt.Font;

/**
 *
 * @author andre
 */
public class LikeDislike extends javax.swing.JDialog {

    /**
     * Creates new form LikeDislike
     */
    public LikeDislike(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButtonLike = new javax.swing.JButton();
        jButtonDislike = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelLike = new javax.swing.JLabel();
        jLabelDislike = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelLikeTitle = new javax.swing.JLabel();
        jLabelDislikeTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(463, 317));

        jPanel3.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jButtonLike.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jButtonLike.setText("Like");
        jButtonLike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLikeActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonLike);

        jButtonDislike.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jButtonDislike.setText("Dislike");
        jButtonDislike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDislikeActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonDislike);

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        jLabelLike.setForeground(new java.awt.Color(102, 255, 102));
        jLabelLike.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLike.setText("👍");
        jPanel1.add(jLabelLike);

        jLabelDislike.setForeground(new java.awt.Color(255, 0, 51));
        jLabelDislike.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDislike.setText("👎");
        jPanel1.add(jLabelDislike);

        jPanel2.setLayout(new java.awt.GridLayout(1, 2, 10, 20));

        jLabelLikeTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabelLikeTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLikeTitle.setText("  ");
        jPanel2.add(jLabelLikeTitle);

        jLabelDislikeTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabelDislikeTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDislikeTitle.setText(" ");
        jPanel2.add(jLabelDislikeTitle);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                .addGap(70, 70, 70))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    int like = 0;
    private void jButtonLikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLikeActionPerformed
        Font f = new Font(jLabelLike.getFont().getFontName(), jLabelLike.getFont().getStyle(), jLabelLike.getFont().getSize()+3);
        jLabelLike.setFont(f);
        aumentarVentana(jLabelLike.getFont().getSize());
        like +=1;
        jLabelLikeTitle.setText(like+"");
    }//GEN-LAST:event_jButtonLikeActionPerformed

    int dislike = 0;
    private void jButtonDislikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDislikeActionPerformed
        Font f = new Font(jLabelDislike.getFont().getFontName(), jLabelDislike.getFont().getStyle(), jLabelDislike.getFont().getSize()+3);
        jLabelDislike.setFont(f);
        aumentarVentana(jLabelDislike.getFont().getSize());
        dislike +=1;
        jLabelDislikeTitle.setText(dislike+"");
    }//GEN-LAST:event_jButtonDislikeActionPerformed

    public void aumentarVentana(int font) {
        if (font > 174) {
            this.setMinimumSize(new Dimension(this.getWidth(), this.getHeight() + 3));
        }
        if (font > 225) {
            this.setMinimumSize(new Dimension(this.getWidth() + 3, this.getHeight()));
        }
        
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDislike;
    private javax.swing.JButton jButtonLike;
    private javax.swing.JLabel jLabelDislike;
    private javax.swing.JLabel jLabelDislikeTitle;
    private javax.swing.JLabel jLabelLike;
    private javax.swing.JLabel jLabelLikeTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
